# This is a config for E2B sandbox template.
# You can use template ID (zzzjvhhffps4bj1lm1lv) or template name (-nextjs-template) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("-nextjs-template") # Sync sandbox
# sandbox = await AsyncSandbox.create("-nextjs-template") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('-nextjs-template')

team_id = "409803d4-c6d0-458f-8abb-e815bc48a727"
dockerfile = "e2b.Dockerfile"
template_name = "-nextjs-template"
template_id = "zzzjvhhffps4bj1lm1lv"
